machine:
  node:
    version: 4.1.1
  pre:
     - curl -k -L -o phantomjs.tar.bz2 https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
     - tar -jxf phantomjs.tar.bz2

language: ruby
rvm:
  - 2.3.1
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bundle exec rspec spec/
addons:
  code_climate:
    repo_token: 32b18973ec4b76776b22ea2024b43d91f89210627487c33597ef3f345ce7bc9a